### ISSUE TITLE
how do we show this plugin on a page ?

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-time-zones#1]
Hi im just missing the instructions on how to show this plugin on a page.

**Comment by raykai** [comment]
or didi not rename the folder the right way ?  is it eve-online-time-zones or EveOnlineTimeZones ? 

i would really like this plugin to work plz help.

**Comment by ppfeufer** [comment]
Create a page (not a post) and set its template to "EVE Time Zones", that basically it.
How the folder is named is only important for automatic updated, and "eve-online-time-zones" is right there.

Plugin is not really finished yet, once done, I'll add a proper readme.

**Comment by raykai** [comment]
yay got it working ty so much :)
